### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tsht99** [tsht99/lib-gas-database#1]
- [ ] setValues で配列の要素が undefined なら上書きされるか、そのままか。
- [ ] #2
- [ ] #3
- [ ] #4
- [ ] 一括上書きメソッドを追加
- [ ] Sheets API で置換
- [ ] read して write するまでに DB が変更されたら検知
